### ISSUE TITLE
Web owin.org charset

### ISSUE THREAD

**Issue by bigpcz** [owin/owin#34] opened 2015-02-15 13:43 UTC
Hi, 

I can see wrong characters in the OWIN spec. extensions:
http://owin.org/spec/extensions/owin-SendFile-Extension-v0.2.0.htm

![qmchar](https://cloud.githubusercontent.com/assets/7683458/6203401/980b6fa4-b520-11e4-9aca-a1414620ed76.png)

It doesn't look professional and should be fixed.

**Comment by serialseb** [comment] 2015-02-15 19:31
Feel free to submit a pull request. I don't know if anyone has their names on that spec.

**Comment by panesofglass** [comment] 2015-02-22 04:17
In particular, we'd love to finish rewriting all these things as markdown. The tokens you see are a result of generating markup from Word.

**Comment by panesofglass** [comment] 2015-10-13 15:38
Duplicate of #18

**Closed by panesofglass** 2015-10-13 15:38 UTC
Labels: Administrative
