### ISSUE TITLE
No owin.Environment item was found in the context in IIS Web Farm ARR hosting

### ISSUE THREAD

**Issue by kolte** [owin/owin#55] opened 2018-03-07 13:36 UTC
I am trying to set load balancing with IIS ARR but getting this error when I try to login, It works find if I test it outside ARR

Server Error in '/' Application. No owin.Environment item was found in the context. Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: No owin.Environment item was found in the context.

**Comment by Tratcher** [comment] 2018-03-07 15:00
Duplicate of https://github.com/aspnet/AspNetKatana/issues/179, please close.

**Closed as completed** 2018-03-07 17:47 UTC
